### ISSUE TITLE
Want Database

### ISSUE THREAD

**Issue by VishalKamaliya** [mlayah/student-fx#1]

**Comment by MHTaleb** [comment]
please provide the database sql script

**Comment by mlayah** [comment]
study the code and make your own schema,i misplaced mine.

**Comment by MHTaleb** [comment]
ok
ones I will make mine I ll send it to you to share it

2017-07-10 19:02 GMT+02:00 Dan Mlayah <notifications@github.com>:

> study the code and make your own schema,i misplaced mine.
>

**Comment by MHTaleb** [comment]
And keep it going you have the designer touch


2017-07-10 19:03 GMT+02:00 Taleb Mohammed Housseyn <talcorpdz@gmail.com>:

> ok
> ones I will make mine I ll send it to you to share it
>
> 2017-07-10 19:02 GMT+02:00 Dan Mlayah <notifications@github.com>:
>
>> study the code and make your own schema,i misplaced mine.
>>

**Comment by mlayah** [comment]
much appreciated

**Comment by chiput** [comment]
please give me structure database, its help to running and learning your project. I'm newbie in javafx
