### ISSUE TITLE
Cant edit fxml files using scene builder

### ISSUE THREAD

**Issue by brunochichava** [mlayah/student-fx#2]
Hi there,

First of all thanks for your code and design, it is a beautifull UI, im having a ilitle issue, i cant open the fxml files with Scene Builder 2.0.

Only the file Login.fxml opens, the others files doesnt open.

You can see the print screens of the error and related stacktrace.

Error: [https://prnt.sc/hv5crs](url)
Stack Trace: [https://prnt.sc/hv5djk](url)

Any help is apreciated, thanks.

**Comment by mlayah** [comment]
Include all libraries in the lib folder to scene builder.
